version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
        #- "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./certificates/acme.json:/certificates/acme.json:rw"
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    labels:
        # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`thibaut-trafeik.duckdns.org`)"
      - "traefik.http.routers.dashboard.entrypoints=web,websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt-duckdns"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH_USER}"
        #- "traefik.http.routers.prometheus.rule=Path(`/metrics`)"
        #- "traefik.http.routers.prometheus.entrypoints=websecure"
        #- "traefik.http.routers.prometheus.tls=true"
  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-proxy.rule=Host(`vps-thibaut.duckdns.org`)"
      - "traefik.http.routers.nginx-proxy.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-proxy.tls=true"
      - "traefik.http.routers.nginx-proxy.tls.certresolver=letsencrypt-duckdns"
      - "traefik.http.routers.nginx-proxy.middlewares=nginx-redirect-to-https"
      - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"
        #prometheus:
        #image: prom/prometheus:latest
        #volumes:
        #- ./prometheus.yml:/etc/prometheus/prometheus.yml
        #ports:
        #- "9090:9090"

