version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./certificates/acme.json:/certificates/acme.json:rw"
    labels:
      - "traefik.enable=true"

        # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.thibaut-trafeik.duckdns.org`)"
      - "traefik.http.routers.dashboard.service=api@internal"
        
        # Router syno
      - "traefik.http.routers.synology-router.rule=Host(`thibaut-trafeik.duckdns.org`)"
      - "traefik.http.routers.synology-router.service=synology-service"
      - "traefik.http.routers.synology-router.entrypoints=web,websecure"
      - "traefik.http.routers.synology-router.tls=true"
      - "traefik.http.routers.synology-router.tls.certresolver=letsencrypt"
      - "traefik.http.routers.synology-router.middlewares=redirect-to-https"

      # Service pour router syno
      - "traefik.http.services.synology-service.loadbalancer.server.url=http://90.127.2.21:5554"

      # Middleware auto redirect to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
