version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./certificates/acme.json:/certificates/acme.json:rw"
    environment:
      - DUCKDNS_TOKEN=66117bf7-54a4-4fc5-a142-ab25c5f8146d
    labels:
        # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.thibaut-trafeik.duckdns.org`)"
      - "traefik.http.routers.dashboard.service=api@internal"
  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-proxy.rule=Host(`nginx.thibaut-trafeik.duckdns.org`)"
      - "traefik.http.routers.nginx-proxy.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-proxy.tls=true"
      - "traefik.http.routers.nginx-proxy.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"
