http:
  routers:
    nas:
      rule: "Host(`homethibaut.synology.me`)"
      service: nas-svc
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

  services:
    nas-svc:
      loadBalancer:
        servers:
          - url: "https://vps-thibaut.duckdns.org"

