[http.routers]
  [http.routers.my-router]
    rule = "Host(`alice-baptiste.duckdns.org`)"
    service = "my-service"
    entryPoints = ["websecure"]
    middlewares = ["https-redirect"]
    [http.routers.my-router.tls]
      certResolver = "myresolver"

[http.middlewares]
  [http.middlewares.https-redirect.redirectScheme]
    scheme = "https"
    permanent = true

[http.services]
  [http.services.my-service.loadBalancer]
    [[http.services.my-service.loadBalancer.servers]]
      url = "https://90.127.2.21"

[tls.certificates]
  [tls.certificates.myresolver]
    acme = {
      email = "pi.raspberry13@gmail.com",
      storage = "acme.json",
      caServer = "https://acme-staging-v02.api.letsencrypt.org/directory",
      [tls.certificates.myresolver.acme.dnsChallenge]
        provider = "duckdns"
    }